eureka:
  client:
    service-url:
      defaultZone: http://192.168.183.133:8761/eureka/,http://192.168.183.142:8761/eureka/
  instance:
    ip-address: ${ip.address}
    prefer-ip-address: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.183.143:3306/test?useUnicode=true&charactorEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
  rabbitmq:
    host: 192.168.183.143
    password: guest
    port: 5672
    username: guest
