eureka:
  client:
    service-url:
      defaultZone: http://192.168.183.133:8761/eureka/,http://192.168.183.142:8761/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.183.143:3306/test?useUnicode=true&charactorEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
